version: "4.3"

services:
  client:
    container_name: assessment-tool-client-container
    restart: always
    ports:
      - "3000:3000"
    build: 
      context: ./client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - /app/node_modules
      - ./client:/app
    